version: "3.7"
services:
  nginx:
    image: nginx:1.22.0-alpine
    container_name: fawkes-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ../app:/var/www/fawkes
      - ./config/nginx:/etc/nginx/conf.d
    networks:
      - fawkes
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: fawkes-app
    restart: unless-stopped
    volumes:
      - ../app:/var/www/fawkes
      - ./config/php:/usr/local/etc/php
    networks:
      - fawkes
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    container_name: fawkes-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - fawkes
networks:
  fawkes: